import { useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import { CheckCircle2, ArrowRight } from 'lucide-react';
import DashboardLayout from '../components/DashboardLayout';
import Syllo from '../components/Syllo';
import './BriefPreview.css';

export default function BriefPreview() {
  const navigate = useNavigate();

  return (
    <DashboardLayout activeItem="AI Recommendations">
      <div className="brief-page">
        <motion.h1
          className="brief-page-title"
          initial={{ opacity: 0, y: -10 }}
          animate={{ opacity: 1, y: 0 }}
        >
          Brief Preview
        </motion.h1>

        {/* Document preview */}
        <motion.div
          className="brief-document"
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.3 }}
        >
          <div className="brief-doc-header">
            <div className="brief-doc-logo">🎓</div>
            <h2>Future-State Curriculum Brief</h2>
            <p className="brief-doc-meta">
              Prepared for: School of Computing Curriculum Committee<br />
              Generated by: Future-State Curriculum Engine<br />
              Date: June 2026
            </p>
          </div>

          <div className="brief-doc-body">
            {/* Section 1 */}
            <div className="brief-section">
              <h3>1. Course Analyzed</h3>
              <div className="brief-info-grid">
                <div><span>Course:</span> Software Engineering</div>
                <div><span>Faculty:</span> School of Computing</div>
                <div><span>University:</span> Northbridge University</div>
                <div><span>Target Year:</span> 2027</div>
              </div>
            </div>

            {/* Section 2 */}
            <div className="brief-section">
              <h3>2. Current Curriculum Coverage</h3>
              <div className="brief-tags">
                {['SDLC', 'UML Diagrams', 'Agile Basics', 'Requirements Engineering', 'Software Testing', 'Documentation'].map((s, i) => (
                  <span key={i} className="brief-tag covered">{s}</span>
                ))}
              </div>
            </div>

            {/* Section 3 */}
            <div className="brief-section">
              <h3>3. Future Skill Demand</h3>
              <div className="brief-tags">
                {['GitHub Workflow', 'CI/CD', 'Cloud Deployment', 'API Testing', 'Docker', 'AI-Assisted Dev', 'Product Analytics'].map((s, i) => (
                  <span key={i} className="brief-tag demand">{s}</span>
                ))}
              </div>
            </div>

            {/* Section 4 */}
            <div className="brief-section">
              <h3>4. Identified Gaps</h3>
              <ul className="brief-gap-list">
                <li>CI/CD pipeline skills not covered</li>
                <li>Docker containerization absent</li>
                <li>Cloud deployment not addressed</li>
                <li>AI-assisted development ethics missing</li>
                <li>Industry collaboration not integrated</li>
              </ul>
            </div>

            {/* Section 5 */}
            <div className="brief-section">
              <h3>5. Recommended Updates</h3>
              <div className="brief-updates">
                {[
                  'Add Practical DevOps Lab',
                  'Replace Final Exam with Product Sprint',
                  'Add Industry Micro-Brief',
                  'Introduce AI Coding Policy',
                  'Add CI/CD Mini Pipeline'
                ].map((u, i) => (
                  <div key={i} className="brief-update-item">
                    <CheckCircle2 size={14} />
                    <span>{u}</span>
                  </div>
                ))}
              </div>
            </div>

            {/* Section 6 */}
            <div className="brief-section highlight">
              <h3>6. Expected Readiness Improvement</h3>
              <div className="brief-score-change">
                <div className="brief-score before">
                  <span className="brief-score-label">Before</span>
                  <span className="brief-score-value">64</span>
                </div>
                <ArrowRight size={20} className="brief-score-arrow" />
                <div className="brief-score after">
                  <span className="brief-score-label">After</span>
                  <span className="brief-score-value">87</span>
                </div>
              </div>
            </div>

            {/* Section 7 */}
            <div className="brief-section">
              <h3>7. Committee Decision Options</h3>
              <div className="brief-options">
                <button
                  className="brief-option-btn primary"
                  onClick={() => navigate('/success')}
                >
                  ✓ Approve for Pilot
                </button>
                <button className="brief-option-btn secondary">
                  📋 Request Faculty Review
                </button>
                <button className="brief-option-btn secondary">
                  💾 Save for Later
                </button>
              </div>
            </div>
          </div>

          {/* Signature area */}
          <div className="brief-signature">
            <div className="brief-sig-line">
              <div className="brief-sig-dash" />
              <span>Authorized Signature</span>
            </div>
            <div className="brief-sig-stamp">
              <motion.div
                className="brief-stamp-inner"
                initial={{ opacity: 0, rotate: -20, scale: 1.4 }}
                animate={{ opacity: 1, rotate: -8, scale: 1 }}
                transition={{ delay: 1, type: 'spring', damping: 8 }}
              >
                REVIEWED
              </motion.div>
            </div>
          </div>
        </motion.div>
      </div>

      <Syllo
        message="The formal brief is ready for the curriculum committee. One step from implementation!"
        pose="wave"
        delay={1.5}
      />
    </DashboardLayout>
  );
}
